# Generated by Django 4.2.1 on 2023-05-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='message',
            new_name='content',
        ),
    ]
