# Generated by Django 4.2.1 on 2023-08-10 06:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(help_text='Укажите номер телефона для связи', max_length=12, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате 8XXXXXXXXXX или +7XXXXXXXXXX.', regex='^(\\+7|8)[0-9]{10}$')], verbose_name='Номер телефона'),
        ),
    ]
